spring.application.name=central-config

server.port=8888

#setting config storage path
spring.cloud.config.server.native.search-locations=file:./src/main/resources/configs
spring.profiles.active=native